spring.application.name=proyungas-files

# Allow larger multipart uploads
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB

#storage.s3.endpoint=http://localhost:3900
storage.s3.endpoint=http://127.0.0.1:3900
storage.s3.region=garage
storage.s3.access-key=GK6be71b0eabe40f16587323a4
storage.s3.secret-key=76fe48cda3397124d4902155d097a9906e35ed5ee40936b83c446a8a922ab79b
storage.s3.bucket=mapas-app